version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-ground

  database:
    image: 'postgres:latest'
    container_name: database-ground
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - ./volumes/db-data/:/var/lib/postgresql/data/

  web:
    container_name: backend_ground
    build:
      context: /backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - database
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
